-- Create review table
CREATE TABLE review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  language TEXT,
  full_name TEXT,
  email TEXT,
  nationality TEXT,
  travel_agent TEXT,
  wildlife_experience TEXT,
  guide TEXT,
  guide_rating TEXT,
  key_sightings TEXT[], -- Array type for multiple selections
  activities TEXT[], -- Array type for multiple selections
  wildlife_comments TEXT,
  accommodation_rating TEXT,
  facilities_rating TEXT,
  food_rating TEXT,
  housekeeping_rating TEXT,
  staff_rating TEXT,
  staff_standout TEXT[], -- Array type for multiple selections
  hospitality_comments TEXT,
  recommend_tuludi TEXT,
  communication_rating TEXT,
  marketing_source TEXT,
  overall_experience TEXT
);

-- Add row level security (RLS)
ALTER TABLE review ENABLE ROW LEVEL SECURITY;

-- Create policy to allow inserts from anyone (including public/anonymous access)
CREATE POLICY "Enable insert for all users" 
ON review FOR INSERT 
TO public
WITH CHECK (true);

-- Create policy to allow reads from authenticated users only
CREATE POLICY "Enable read access for authenticated users only" 
ON review FOR SELECT 
TO authenticated 
USING (true); 