-- Create review table
CREATE TABLE review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  language TEXT NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  nationality TEXT NOT NULL,
  travel_agent TEXT,
  wildlife_experience TEXT NOT NULL,
  guide TEXT NOT NULL,
  guide_rating TEXT NOT NULL,
  key_sightings TEXT[], -- Array type for multiple selections
  activities TEXT[], -- Array type for multiple selections
  wildlife_comments TEXT,
  accommodation_rating TEXT NOT NULL,
  facilities_rating TEXT NOT NULL,
  food_rating TEXT NOT NULL,
  housekeeping_rating TEXT NOT NULL,
  staff_rating TEXT NOT NULL,
  staff_standout TEXT[], -- Array type for multiple selections
  hospitality_comments TEXT,
  recommend_tuludi TEXT NOT NULL,
  communication_rating TEXT NOT NULL,
  marketing_source TEXT NOT NULL,
  overall_experience TEXT NOT NULL
);

-- Add row level security (RLS)
ALTER TABLE review ENABLE ROW LEVEL SECURITY;

-- Create policy to allow inserts from anyone (including public/anonymous access)
CREATE POLICY "Enable insert for all users" 
ON review FOR INSERT 
TO public
WITH CHECK (true);

-- Create policy to allow reads from authenticated users only
CREATE POLICY "Enable read access for authenticated users only" 
ON review FOR SELECT 
TO authenticated 
USING (true); 